In [1]:
#perceptron 
import numpy as np

In [13]:
#create a sigmoid fuction which return numbers between 0 and 1 only
def sigmoid(x):
    return 1 / (1+np.exp(-x))  #sigmoid function

def sigmoid_derivative(x):
    return x * (1-x)

In [7]:
#Define the training inputs and outputs
training_inputs = np.array([[0,0,1], #this is the input to our network 3x4 matrix
                          [1,0,1],
                          [1,0,1],
                          [0,1,0]])

training_outputs = np.array([[0,1,1,0]]).T

In [5]:
#Initializing weights with random values (-1) - (1)
np.random.seed(1)

synaptic_weights = 2 * np.random.random((3,1)) -1
print('Random starting synaptic weights : ')
print(synaptic_weights)

Random starting synaptic weights : 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [23]:
#creating the loop for training 
for iteration in range(100000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer,synaptic_weights))
    
#print('output after training :')
#print(outputs)

Normally after training we should get outputs like training_outputs i.e [0,1,1,0]
This is why we need a training process.The training process is shown below:
1.Take the inputs from the training example and put them throgh the formula to get the neurons o/p
2.Then we calculate the error which is the difference between the output we got and the actual output
3.Depending on the severeness of the error ,adjust the weights accordingly
4.Repeat the process 20,000 times
This whole process is called backpropagation

Error Weighted Derivative:
One might wonder by which values we have to adjust the weights for that we use
error weighted Derivative:\n
Adjusted Weights = error.input.phi'(output)
    Error = output-actual output
    input = either 1 or 0  (see notes)

In [24]:
#calculting the error
error = training_outputs - outputs  #actual op
adjustments = error * sigmoid_derivative(outputs)
synaptic_weights +=np.dot(input_layer.T,adjustments)

print('synaptic weights  after training :')
print(synaptic_weights)
print('output after training :')
print(outputs)

synaptic weights  after training :
[[ 1.51549282]
 [-0.47804764]
 [ 0.08572842]]
output after training :
[[0.54415707]
 [0.83875117]
 [0.83875117]
 [0.40610214]]
